---
name: book_worm
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=3.5.0-167.0.dev <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^14.1.4
  flutter_svg: ^2.0.5
  google_fonts: ^6.2.1
  dio: ^5.4.3
  flutter_bloc: ^8.1.6
  get_it: ^7.7.0
  cached_network_image: ^3.3.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
  assets:
  - assets/images/
  fonts:
  - family: GT Sectra Fine
    fonts:
    - asset: assets/fonts/GT-Sectra-Fine-Regular.ttf
